### ISSUE TITLE
卡在最后一步...好想看bw阿...草

### ISSUE THREAD

**Issue by saladsandwiches** [akaimoe/BilibiliTicketRushBuy#12]
卡住了....我尽力了...chrome也安了 但是最后网站还是跳不出来 该咋办 求指导
![112](https://github.com/akaimoe/BilibiliTicketRushBuy/assets/139019173/7d7e5855-e550-4173-8eab-70c4e1a762da)

**Comment by akaimoe** [comment]
先pip list看一下有没有selenium，如果有的话就把代码换到一个纯英文路径下试着运行一下（感觉你运行的方式不对，直接在项目路径下启动终端，然后输入python Main.py回车就可以了

**Comment by saladsandwiches** [comment]
> 先pip list看一下有没有selenium，如果有的话就把代码换到一个纯英文路径下试着运行一下（感觉你运行的方式不对，直接在项目路径下启动终端，然后输入python Main.py回车就可以了

解决了！确实是换了一个运行方式之后就可以了！万分感谢...!
