### ISSUE TITLE
票种不同呢？

### ISSUE THREAD

**Issue by chengxupen** [akaimoe/BilibiliTicketRushBuy#15]
就像bw有VIP票，原神典藏票等等，这个是怎么解决的？(顺便问一句，可以用来抢bw嘛，购买人怎么解决的？)

**Comment by XEnderjack** [comment]
可以右键检查然后复制这个按钮的xpath

**Comment by akaimoe** [comment]
已更新票种选择功能，具体使用方法readme写在readme里面了

**Comment by Medic-cn** [comment]
> 已更新票种选择功能，具体使用方法readme写在readme里面了

第21行错别字😰

**Comment by akaimoe** [comment]
> > 已更新票种选择功能，具体使用方法readme写在readme里面了
> 
> 第21行错别字😰

下饭咯233333
