### ISSUE TITLE
大家都抢到了么

### ISSUE THREAD

**Issue by WayneCommand** [akaimoe/BilibiliTicketRushBuy#24]
没有抢到，为什么开着挂都抢不到。。。。

**Comment by ggallgg** [comment]
估计开挂的人也很多。。

**Comment by hanser12345** [comment]
太难了，说明别人的更强

**Comment by ZianTT** [comment]
开挂的确实挺多（更别说基于chrome的能不能比得过纯api检测的

**Comment by akaimoe** [comment]
> 开挂的确实挺多（更别说基于chrome的能不能比得过纯api检测的

确实，现在黄牛用的那种脚本估计都是api检测的，而且很多都是多开，成功率自然也会高一些，这个项目只能说是模拟人类操作的极限速度，差距还是有的，后期有时间了研究一下api检测的办法吧（画饼

**Comment by ZianTT** [comment]
> > 开挂的确实挺多（更别说基于chrome的能不能比得过纯api检测的
> 
> 确实，现在黄牛用的那种脚本估计都是api检测的，而且很多都是多开，成功率自然也会高一些，这个项目只能说是模拟人类操作的极限速度，差距还是有的，后期有时间了研究一下api检测的办法吧（画饼

要不看看我的（什
https://github.com/ZianTT/bilibili-hyg/

**Comment by akaimoe** [comment]
> > > 开挂的确实挺多（更别说基于chrome的能不能比得过纯api检测的
> > 
> > 
> > 确实，现在黄牛用的那种脚本估计都是api检测的，而且很多都是多开，成功率自然也会高一些，这个项目只能说是模拟人类操作的极限速度，差距还是有的，后期有时间了研究一下api检测的办法吧（画饼
> 
> 要不看看我的（什 https://github.com/ZianTT/bilibili-hyg/

思路不错，我找个时间也抓个包玩玩，后面把api检测更新到新的GUI里面去。话说b站的风控你有找到什么规律吗

**Comment by ZianTT** [comment]
> 思路不错，我找个时间也抓个包玩玩，后面把api检测更新到新的GUI里面去。话说b站的风控你有找到什么规律吗

业务风控（412）应该是针对请求速率来封的，和cc防护的原理差不多的样子，小电视应该是全局的速率限制，因为我看人少的时候不会触发，所以我觉得速率限制就全力发包就好

**Comment by WayneCommand** [comment]
明年再战吧！
