### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lrastar** [akaimoe/BilibiliTicketRushBuy#26]
<img width="896" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/dec3cffe-3c89-473c-8ec5-f241a93bc003">
这个是浏览器没配置正确所造成的吗？

**Comment by akaimoe** [comment]
应该是游览器版本不对造成的，要使用chrome的正式版本

**Comment by lrastar** [comment]
> 应该是游览器版本不对造成的，要使用chrome的正式版本

<img width="1280" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/9dc03ccd-df8a-497f-83d3-e2274c77a0b9">
浏览器是正式版本但是，还是这样
<img width="1280" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/8a7b30ba-9d6d-42fc-b3df-a8837b10aba4">
是因为编译器上     WebDriver = webdriver.Chrome(chrome_options=ch_options)    这个标红的原因吗？
<img width="1280" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/9aaaaee5-be4f-411e-9a59-67bda599e1d9">
如果是这个原因的话怎么解决呢？

**Comment by akaimoe** [comment]
那应该就是chromedriver版本的问题了，你要不就下载更高版本的chromedriver装上，要不就把chrome的版本退回到114

**Comment by lrastar** [comment]
> 那应该就是chromedriver版本的问题了，你要不就下载更高版本的chromedriver装上，要不就把chrome的版本退回到114

好我试试，还有难道不是编译器标红的问题吗？

**Comment by akaimoe** [comment]
> > 那应该就是chromedriver版本的问题了，你要不就下载更高版本的chromedriver装上，要不就把chrome的版本退回到114
> 
> 好我试试，还有难道不是编译器标红的问题吗？

emmmmm,你的截图里面好像没出现标红的地方？

**Comment by lrastar** [comment]
@akaimoe 
<img width="832" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/4e6b1077-31c9-4986-9549-37a6f5d18aa6">
这里

**Comment by lrastar** [comment]
@akaimoe 
<img width="728" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/4d44ccd5-6bfe-4f8b-98c2-d760888ed8d1">
<img width="902" alt="image" src="https://github.com/akaimoe/BilibiliTicketRushBuy/assets/143856673/04c65730-85d1-4efe-a243-fcf1913d58e3">浏览器版本114还是一样。

**Comment by sugarcanecat** [comment]
我也是这个问题，浏览器版本也是最新的，出现的界面一样
