### ISSUE TITLE
关于关闭去支付窗口

### ISSUE THREAD

**Issue by LingBai0703** [akaimoe/BilibiliTicketRushBuy#7]
鄙人不才，过几天的bw开票想用这个脚本抢（在校无法准点抢票）但是在实践过程中发现在抢到一张票之后，统一展会的不同时间会提示要先完成支付，然后卡住不再连续点击支付按钮，但由于自己不是很熟悉Python的自动化，所以更改代码实现自动点击取消失败，想请问一下大佬，对于这种按钮该用什么办法实现自动点击，望回复，谢谢

**Comment by LingBai0703** [comment]
已自行解决，实现bw三天自动抢票

**Comment by golo1940** [comment]
> 已自行解决，实现bw三天自动抢票

大佬，能看看你的项目吗？

**Comment by LingBai0703** [comment]
太烂了，抢完这波票再放出吧
